version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.0.0
    command: jekyll serve
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      BUNDLE_PATH: "/usr/gem"